### ISSUE TITLE
Retrieving the resulting path

### ISSUE THREAD

**Issue by 1j01** [velocityzen/fsu#1]
Using `writeFileUnique` I don't know if you can get the actual path it writes to.
After switching to write streams and looking at the source code I was able to find a way to get the path:

``` coffee
ws = fsu.createWriteStreamUnique(outputFile)
blablabla.pipe(ws)
ws.on "open", ->
    console.log "output to #{ws.path}"
```

You should be able to get the path written to with any of the methods.

**Comment by velocityzen** [comment]
All callbacks have a new path as last argument
