### ISSUE TITLE
v1.1.0 doesn't work with older version of Node

### ISSUE THREAD

**Issue by woodcockjosh** [velocityzen/fsu#5]
Hi, 

Looks like the latest version just broke our build. We are running an older version of node v4.3.0 and some package we use mochawesome uses a package mochawesome-report-generator which uses fsu with permissive versioning. so your 1.0.4 has been upgraded to 1.1.0. if you want to add es6 like features like the spread operator I think you should do a major upgrade to 2.0.0. Anyway damage is now done. Not sure what can be done.

**Comment by velocityzen** [comment]
@woodcockjosh I'll rerelease the older version. Consider to update your node. v4 is not supported anymore https://github.com/nodejs/Release#release-schedule

**Comment by woodcockjosh** [comment]
Yes, agree. I'm not sure why we're using v4 as now we're 5 major versions
behind :-(.

**Comment by velocityzen** [comment]
@woodcockjosh I published new version without spread operator at all!

**Comment by velocityzen** [comment]
@woodcockjosh let me know if helped!

**Comment by woodcockjosh** [comment]
Awesome! Thanks!

**Comment by woodcockjosh** [comment]
Problem was resolved with release of 1.1.1. Thank you!
